blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.RSS import PostFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls', namespace='blog')),
    path('haystack/', include('haystack.urls')),
    path('feed/', PostFeed(), name='feed'),
]

blog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from myblog import views
from myblog.RSS import PostFeed


# 设置命名空间需要加上 app_name
app_name = 'myblog'
urlpatterns = [
    path('index/', views.Index.as_view(), name='index'),
    re_path('detail/(?P<pk>\d*)', views.Detail.as_view(), name='detail'),

    # path('achives/', views.Archives.as_view(), name='archives'),
]

blog/myblog/models.py
from django.db import models
from django.contrib.auth.models import User

import markdown
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name = u"分类名字")

    class Meta:
        verbose_name = u"分类"
        verbose_name_plural = verbose_name
        db_table = 'category'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"标签")

    class Meta:
        verbose_name = u"标签"
        verbose_name_plural = verbose_name
        db_table = 'tag'

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200,verbose_name=u"标题")
    body = models.TextField(verbose_name=u"文章正文")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name=u'添加时间')
    modify_time = models.DateTimeField(auto_now=True, verbose_name=u'修改时间')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name=u'文章摘要')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=u'文章分类')
    tags = models.ManyToManyField(Tag, verbose_name=u'标签')
    user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name=u'作者')
    views = models.PositiveIntegerField(default=0, verbose_name=u'阅读量')

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = verbose_name
        db_table = 'post'

    def __str__(self):
        return self.title
#
# # 重写保存方法
# 	def save(self, *args, **kwargs):
# 		# 如果没有摘要， 从body取出一部分
# 		if not self.excerpt:
# 			# 实例化md，用于渲染body文本
# 			md = markdown.Markdown(extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite'])
# 		# 将md文本渲染成html
# 		# strip_tags 去掉html文本的全部html标签
# 		# 摘取body前54个给excerpt
# 		self.excerpt = strip_tags(md.convert(self.body))[:54]

class Comment(models.Model):
    name = models.CharField(max_length=100, verbose_name=u'评论者姓名')
    email = models.EmailField(verbose_name=u'邮箱')
    personal_website = models.CharField(max_length=200, verbose_name='个人网站')
    comment = models.TextField(verbose_name='评论')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=u'文章')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'comment'
        verbose_name = u'评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.base import View
from myblog import models
from django.core.paginator import Paginator
from django.contrib.syndication.views import Feed

import markdown
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger


# 主页
class Index(View):
	def get(self, request):
		post_list = models.Post.objects.all().order_by('-create_time')
		# 查询出归档日期的文章
		year = request.GET.get('year', '')
		month = request.GET.get('month', '')
		category = request.GET.get('category', '')
		tag = request.GET.get('tag', '')
		if year and month:
			post_list = models.Post.objects.filter(create_time__year=int(year), create_time__month=int(month)) \
				.order_by('-create_time')
		# 查询出分类的文章
		if category:
			post_list = models.Post.objects.filter(category__name=category)
		if tag:
			post_list = models.Post.objects.filter(tags=tag)
		# 使用pure_pagination 进行分页代码
		try:
			page = request.GET.get('page', 1)
		except:
			page = 1
		p = Paginator(post_list, 3, request=request)   # 中间的1 是每页显示的数量
		posts = p.page(page)
		# 查询出总共页数
		p = Paginator(post_list, 3)
		page_total = p.num_pages

		# 使用 django pagintor 进行分页代码
		# page_num = int(request.GET.get('page', 1))
		# p = Paginator(post_list, 1)
		# if int(page_num) == 1:
		# 	x = 1
		# else:
		# 	x = int(page_num)
		# 	x = x - 1
		# if page_num == p.num_pages:
		# 	y = int(p.num_pages)
		# else:
		# 	y = int(page_num)
		# 	y = y+1
		# page_total = p.num_pages
		# post_list = p.page(1)
		return render(request, 'myblog/index.html', locals())

	def post(self, request):
		search_feild = request.POST.get('search', '')
		post_list = models.Post.objects.filter(title__icontains=search_feild)
		try:
			page = request.GET.get('page', 1)
		except:
			page = 1
		p = Paginator(post_list, 3, request=request)  # 中间的1 是每页显示的数量
		posts = p.page(page)
		# 查询出总共页数
		p = Paginator(post_list, 3)
		page_total = p.num_pages
		return render(request, 'myblog/index.html', locals())


# 文章详细信息
class Detail(View):
	def get(self, request, pk):
		# get_object_or_404 有两个参数，第一个是查询源，第二个条件，如果查询为空返回404页面
		post = get_object_or_404(models.Post, id=pk)
		# markdown标记语言
		# post.body = markdown.markdown(post.body, extensions=[
		# 	'markdown.extensions.extra',
		# 	'markdown.extensions.codehilite',
		# 	'markdown.extensions.toc',
		# ])
		comments = models.Comment.objects.filter(post_id=int(pk))
		# 标记语言以及生成目录列表
		md = markdown.Markdown(extensions=[
			'markdown.extensions.extra',
			'markdown.extensions.codehilite',
			'markdown.extensions.toc',
		])
		post.body = md.convert(post.body)
		toc = md.toc
		# post.increase_views用来自增长阅读量
		post.increase_views()
		return render(request, 'myblog/single.html', locals())

	def post(self, request, pk):
		search_field = request.POST.get('search', '')
		post_list = models.Post.objects.filter(title__icontains=search_field)
		if search_field:
			try:
				page = request.GET.get('page', 1)
			except:
				page = 1
			p = Paginator(post_list, 3, request=request)  # 中间的1 是每页显示的数量
			posts = p.page(page)
			# 查询出总共页数
			p = Paginator(post_list, 3)
			page_total = p.num_pages
			return render(request, 'myblog/index.html', locals())
		else:
			name = request.POST.get('name', '')
			email = request.POST.get('email', '')
			url = request.POST.get('url', '')
			comment = request.POST.get('comment', '')
			new_comment = models.Comment()
			new_comment.post_id = int(pk)
			new_comment.name = name
			new_comment.email = email
			new_comment.personal_website = url
			new_comment.comment = comment
			new_comment.save()
			return redirect('/myblog/detail/{0}'.format(pk))


# 归档显示
# class Archives(View):
# 	def get(self, request):
# 		year = request.GET.get('year', '')
# 		month = request.GET.get('month', '')
# 		# 条件查询出某年某月的文章
# 		post_list = models.Post.objects.filter(create_time__year=int(year), create_time__month=int(month ))\
# 			.order_by('-create_time')
# 		return render(request, 'myblog/index.html', locals())

# Create your views here.
# class Search_post(View):
# 	def post(self):

class Formyself(View):
	pass


# RSS订阅
# class LastestEntries(Feed):
# 	title = 'GBXZ'
# 	link = '/myblog/'

blog/myblog/templates/myblog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

blog/myblog/templates/myblog/base.html
{% load staticfiles %}
{% load  blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>GBXZ的博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="shortcut icon" href="{% static 'img/s.ico' %}" type="image/x-icon"/>
    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
{#                    <h1><a href="index.html"><b>GBXZ</b> & BLOG</a></h1>#}
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myblog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="post" id="searchform">
                            {% csrf_token %}
                            <input name="search" type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
               {% block main %}
			   {% endblock %}
            </main>
            <aside class="col-md-4">
               {% block aside %}
                 {% endblock %}
                      <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_posts_list %}
                    <ul>
                        {% for post in recent_posts_list %}
                        <li>
                            <a href="{% url 'myblog:detail' post.id  %}">{{ post.title }}</a>
                        </li>
                            {% empty %}
                            暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'myblog:index' %}?year={{ date.year }}&month={{ date.month }}">{{ date.year}}年{{date.month}}月</a>
                        </li>
                      {% empty %}
                            暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                          {% get_categories as category_list %}
                            {% for category in category_list %}
                        <li>
                            <a href="{% url 'myblog:index' %}?category={{ category.name }}">{{ category.name }}<span class="post-count">({{ category.post_set.count }})</span></a>
                        </li>
                                {% empty %}
                                暂无分类
                            {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% tag as tags %}
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'myblog:index' %}?tag={{ tag.name }}">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
{#                        <li>#}
{#                            <a href="#">Python</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Java</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">笔记</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">文档</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">AngularJS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">CSS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">JavaScript</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Snippet</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">jQuery</a>#}
{#                        </li>#}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'feed' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>

            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - <a target="_blank">粤ICP备18117587号</a> - <a target="_blank" title="模板之家">GBXZ</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

blog/myblog/templates/myblog/index.html
{% extends 'myblog/base.html'%}
{% load static %}
{% load blog_tags %}
			{% block main %}
                {% for post in posts.object_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'myblog:detail' post.id %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{post.category.name}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{post.create_time.year}}年{{post.create_time.month}}月{{post.create_time.day }}日</time></a></span>
                            <span class="post-author"><a href="#">{{ post.user.username }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.body|truncatechars_html:50 }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'myblog:detail' post.id %}" class="more-link">阅读更多 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% endfor %}


                <div class="pagination-simple">
                {% if posts.has_previous %}
                    <a href="?{{ posts.previous_page_number.querystring }}">上一页</a>
                    {% endif %}
                    <span class="current">第 {{ page }} 页 / 共 {{ page_total }} 页</span>
                {% if posts.has_next %}
                    <a href="?{{ posts.next_page_number.querystring }}">下一页</a>
                {% endif %}
                </div>

{#                <div class="pagination">#}
{#                    {{ posts.render }}#}
{#                </div>#}

{##}
{#                <div class="pagination">#}
{#                    <ul>#}
{#                        <li><a href="">1</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">4</a></li>#}
{#                        <li><a href="">5</a></li>#}
{#                        <li class="current"><a href="">6</a></li>#}
{#                        <li><a href="">7</a></li>#}
{#                        <li><a href="">8</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">11</a></li>#}
{#                    </ul>#}
{#                </div>#}
				{% endblock %}

 
  

blog/myblog/templates/myblog/single.html
{% extends 'myblog/base.html'%}
{% load static %}


{% block main  %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{post.title}}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.create_time.year }}年{{ post.create_time.month }}月{{ post.create_time.day }}日</time></a></span>
                            <span class="post-author"><a href="#">{{ post.user.username }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{post.body|safe}}</p>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form  method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comments %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.create_time.year }}年{{ comment.create_time.month }}月{{ comment.create_time.day }}日 {{ comment.create_time.hour }}:{{ comment.create_time.minute }}</time>
                                <div class="text">
                                  {{ comment.comment }}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>
				{% endblock %}
{% block aside %}
<div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">教程特点</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">谁适合这个教程</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">在线预览</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">资源列表</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">{{ toc|safe }}</a>#}
{#                        </li>#}
{#                    </ul>#}
                 {{ toc|safe }}
                </div>
{% endblock %}